version: "3.9"

services:
    seq:
        image: datalust/seq
        ports:
            - 5341:5341
            - 5342:80
        volumes:
            - rps_seq_data:/data
        environment:
            - ACCEPT_EULA=Y
    
    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411
        environment:
            - STORAGE_TYPE=mysql
            - MYSQL_HOST=zipkin-storage
            - MYSQL_USER=zipkin
            - MYSQL_PASS=zipkin
        depends_on: 
            - zipkin-storage
    
    zipkin-storage:
        image: openzipkin/zipkin-mysql
        ports:
            - 3306:3306
        volumes:
            - zipkin_data:/mysql/data
    
    cache-db:
        image: "mysql"
        environment:
            MYSQL_DATABASE: "cache-database"
            MYSQL_USER: "div-cache"
            MYSQL_PASSWORD: "C@ch3d1v"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    
    add-service:
        build:
            context: .
            dockerfile: AddService/Dockerfile
        depends_on:
            -   cache-db
        deploy: 
            replicas: 1
        ports:
            -   5001:80
    subtract-service:
        build:
            context: .
            dockerfile: SubtractService/Dockerfile
        depends_on:
            - cache-db
        ports:
            -   5002:80
        deploy:
            replicas: 1
    calculator-service:
        build:
            context: .
            dockerfile: CalculatorService/Dockerfile
        ports:
             - 8080:80
        depends_on:
            - add-service
            - subtract-service
        deploy:
            replicas: 1
volumes:
    rps_seq_data:
    zipkin_data: